/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: apps\web\src\theme\hive-theme.config.mjs
 * Command: astryx theme build apps\web\src\theme\hive-theme.config.mjs
 * Generated: 2026-07-21T18:14:33.502Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const hiveTheme: DefinedTheme;
