// Generated by scripts/generate-desktop-preload.mjs. Do not edit by hand.
const { contextBridge, ipcRenderer } = require("electron");

const REQUEST_CHANNEL = "hive-desktop:request";
const EVENT_CHANNEL = "hive-desktop:event";
const COMMANDS = new Set([
  "repository.list",
  "repository.open",
  "thread.list",
  "thread.create",
  "thread.load",
  "thread.message.append",
  "thread.archive",
  "run.start",
  "run.pause",
  "run.resume",
  "run.cancel",
  "run.report",
  "provider.list",
  "provider.metadata",
  "provider.configure",
  "credential.list",
  "credential.metadata",
  "credential.set",
  "credential.replace",
  "credential.remove",
  "credential.test",
  "git.inspect",
  "changes.diff",
  "git.commit.preview",
  "git.commit.confirm",
  "git.push.preview",
  "git.push.confirm",
  "git.pull-request.preview",
  "git.pull-request.confirm",
  "git.discard.preview",
  "git.discard.confirm",
  "external.open-editor",
  "external.open-terminal",
  "external.open-explorer"
]);

function validatedCommand(value) {
  if (!value || typeof value !== "object" || Array.isArray(value) || typeof value.type !== "string" || !COMMANDS.has(value.type)) throw new TypeError("Unsupported HIVE desktop command.");
  if (typeof value.requestId !== "string" || !/^[A-Za-z0-9][A-Za-z0-9._-]{0,95}$/.test(value.requestId)) throw new TypeError("Invalid HIVE desktop request id.");
  const serialized = JSON.stringify(value);
  if (!serialized || serialized.length > 256_000) throw new TypeError("HIVE desktop command is too large.");
  return JSON.parse(serialized);
}

function validatedEvent(value) {
  if (!value || typeof value !== "object" || Array.isArray(value) || typeof value.type !== "string" || typeof value.timestamp !== "string") throw new TypeError("Malformed HIVE desktop event.");
  const serialized = JSON.stringify(value);
  if (!serialized || serialized.length > 1_000_000) throw new TypeError("HIVE desktop event is too large.");
  return JSON.parse(serialized);
}

contextBridge.exposeInMainWorld("hiveDesktop", Object.freeze({
  request(command) { return ipcRenderer.invoke(REQUEST_CHANNEL, validatedCommand(command)).then(validatedEvent); },
  subscribe(listener) {
    if (typeof listener !== "function") throw new TypeError("HIVE desktop listener must be a function.");
    const handler = (_event, payload) => listener(validatedEvent(payload));
    ipcRenderer.on(EVENT_CHANNEL, handler);
    return () => ipcRenderer.removeListener(EVENT_CHANNEL, handler);
  },
}));
